title: sysop71.com
author:
  name: "sysop71#1297"
  email: gamer@sysop71.com

description: >-
  Your go-to hub for gaming streams, e-sports highlights, and personal tech insights.
url: "https://sysop71.com"

# Build settings
markdown: kramdown
remote_theme: jekyll/minima
#theme: minima

collections:
  tournaments:
    platform:
    competitive:
    team:
    sub:
    date:
    output: true
  calendars:
    title:
    month:
    year:
    output: true

minima:
  skin: dark
  show_excerpts: true
  nav_pages:
    - posts.md
    - tournaments.md
    - calendar.md
    - streaming.md
    - series.md
    - about.md
  social_links:
    - title: My TikTok clips
      icon: tiktok
      url: "https://www.tiktok.com/@sysop71"
    - title: Wave Hello
      icon: discord
      url: "https://discord.gg/BYAjAqXEpp"
    - title: My Instagram feed
      icon: instagram
      url: "https://www.instagram.com/sysop71/"
    - title: Watch my stream
      icon: twitch
      url: "https://twitch.tv/sysop71"
    - title: My YouTube channel
      icon: youtube
      url: "https://www.youtube.com/@sysop71"
    - title: Come chat with me
      icon: bluesky
      url: "https://bsky.app/profile/sysop71.bsky.social"

# Disqus Comments
disqus:
    shortname: https-sysop71-com

google_analytics: G-8CXKYEE42R

paginate: 5
paginate_path: /posts/page:num

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
#  - jekyll-include-cache
