# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: sysop71.com
description: >- # this means to ignore newlines until "baseurl:"
  Your go-to hub for gaming streams, e-sports highlights, and personal tech insights.
#baseurl: "/pattontech" # the subpath of your site, e.g. /blog
url: "https://sysop71.com" # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: "sysop71#1297"
  email: gamer@sysop71.com

google_analytics: G-8CXKYEE42R

show_excerpts: true

paginate: 5
paginate_path: /posts/page:num

header_pages:
 - posts.md
 - tournaments.md
 - calendar.md
 - streaming.md
 - about.md

# Build settings
markdown: kramdown
remote_theme: jekyll/minima
#theme: minima

collections:
  tournaments:
    platform:
    competitive:
    team:
    sub:
    date:
    output: true
  calendars:
    title:
    month:
    year:
    output: true

minima:
  skin: dark
  social_links:
    - platform: tiktok
      user_url: "https://www.tiktok.com/@sysop71"
      title: My TikTok clips
    - platform: discord
      user_url: "https://discord.gg/BYAjAqXEpp"
      title: Wave Hello
    - platform: instagram
      user_url: "https://www.instagram.com/sysop71/"
      title: My Instagram feed
    - platform: twitch
      user_url: "https://twitch.tv/sysop71"
      title: Watch my stream
    - platform: youtube
      user_url: "https://www.youtube.com/@sysop71"
      title: My YouTube channel
    - platform: bsky
      user_url: "https://bsky.app/profile/sysop71.bsky.social"
      title: Come chat with me


#remote_theme: pages-themes/midnight@v0.2.0
#remote_theme: mmistakes/minimal-mistakes

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: https-sysop71-com

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
#  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
