name: 'Update Refresh Token Secret'
description: 'Action to update the refresh token secret in GitHub'

inputs:
  github_token:
    description: 'GitHub token to authenticate the request'
    required: true
  new_refresh_token:
    description: 'New refresh token to store as a GitHub secret'
    required: true

runs:
  using: 'python3'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run custom Python script to update refresh token secret
      run: |
        python3 ./.github/actions/update-refresh-token/update_secret.py
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        NEW_REFRESH_TOKEN: ${{ inputs.new_refresh_token }}
