name: 'Update Refresh Token Secret'
description: 'Action to update the refresh token secret in GitHub'

inputs:
  github_token:
    description: 'GitHub token to authenticate the request'
    required: true
  new_refresh_token:
    description: 'New refresh token to store as a GitHub secret'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run update script
      shell: bash
      run: |
        echo "Encrypting the new refresh token..."
        public_key=$(curl -s -H "Authorization: Bearer ${{ inputs.github_token }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/secrets/public_key | jq -r '.key')
        encrypted_value=$(python3 -c "
import base64
from nacl import encoding, public
key = public.PublicKey(bytes.fromhex('${public_key}'), encoding.HexEncoder())
sealed_box = public.SealedBox(key)
encrypted = sealed_box.encrypt('${{ inputs.new_refresh_token }}'.encode())
print(base64.b64encode(encrypted).decode())")
        curl -X PUT \
          -H "Authorization: Bearer ${{ inputs.github_token }}" \
          -H "Accept: application/vnd.github+json" \
          -d "{\"encrypted_value\":\"$encrypted_value\",\"key_id\":\"${public_key}\"}" \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/secrets/REFRESHTOKEN
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
