name: YouTube Backfill Metrics

on:
  workflow_dispatch:  # Manually triggered from the UI

env:
  ACTIONS_RUNNER_DEBUG: false
  ACTIONS_STEP_DEBUG: false

jobs:
  backfill-youtube-metrics:
    runs-on: windows-latest  # Use Windows for PowerShell compatibility

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Retrieve YouTube Refresh Token from Azure Key Vault
        id: get-refresh-token
        shell: pwsh
        run: |
          $KeyVaultName = "${{ secrets.AZURE_KEYVAULT_NAME }}"
          $SecretName = "YouTube-RefreshToken"
          $RefreshToken = az keyvault secret show --vault-name $KeyVaultName --name $SecretName --query value -o tsv
          if (-not $RefreshToken) {
              Write-Error "Failed to retrieve the refresh token from Azure Key Vault."
              exit 1
          }
          Write-Host "Refresh token retrieved successfully"
          echo "refresh_token=$RefreshToken" >> $GITHUB_ENV

      - name: Get YouTube Access Token using Refresh Token
        id: get-access-token
        shell: pwsh
        run: |
          $ClientId = "${{ secrets.YT_CLIENT_ID }}"
          $ClientSecret = "${{ secrets.YT_CLIENT_SECRET }}"
          $RefreshToken = "${{ env.refresh_token }}"

          # Make the API request to get the access token using the refresh token
          $TokenResponse = Invoke-RestMethod -Uri "https://oauth2.googleapis.com/token" -Method Post -Body @{
              client_id     = $ClientId
              client_secret = $ClientSecret
              refresh_token = $RefreshToken
              grant_type    = "refresh_token"
          } -ContentType "application/x-www-form-urlencoded"

          $AccessToken = $TokenResponse.access_token
          Write-Host "Access token retrieved successfully"
          echo "access_token=$AccessToken" >> $GITHUB_ENV

      - name: Install and Import PoshMongo Module
        shell: pwsh
        run: |
            # Install the PoshMongo module from the PowerShell Gallery
            Install-Module -Name PoshMongo -Force -Scope CurrentUser

            # Import the PoshMongo module
            Import-Module PoshMongo

            # Validate that the module is loaded correctly and cmdlet exists
            if (-not (Get-Command -Name 'Connect-MongoDBInstance' -ErrorAction SilentlyContinue)) {
                Write-Error "PoshMongo module did not load correctly or Connect-MongoDBInstance cmdlet is not available."
                exit 1
            } else {
                Write-Host "PoshMongo module loaded successfully, and Connect-MongoDBInstance cmdlet is available."
            }

      - name: Collect YouTube Metrics for Backfill
        id: collect-youtube
        shell: pwsh
        run: |
          # Get the channel ID from the repository variable
          $ChannelId = "${{ vars.CHANNEL_ID }}"

          # Define the YouTube Analytics API endpoint
          $ApiUrl = "https://youtubeanalytics.googleapis.com/v2/reports"

          # Get the start date (first day of the year)
          $StartDate = "2025-01-01"  # Adjust if the year changes dynamically
          $EndDate = (Get-Date).ToString("yyyy-MM-dd")  # Today's date

          # Retrieve the access token
          $AccessToken = "${{ env.access_token }}"
          if (-not $AccessToken) {
            Write-Error "Access token is missing. Authentication failed."
            exit 1
          }

          # Import the PoshMongo module
          Import-Module PoshMongo

          # Validate that the module is loaded correctly and cmdlet exists
          if (-not (Get-Command -Name 'Connect-MongoDBInstance' -ErrorAction SilentlyContinue)) {
              Write-Error "PoshMongo module did not load correctly or Connect-MongoDBInstance cmdlet is not available."
              exit 1
          }

          # Connect to MongoDB once before the loop
          $MongoUri = "${{ secrets.MONGODB_URI }}"
          $MongoDbName = "metrics"
          $MongoCollection = "youtube"

          $MongoClient = Connect-MongoDBInstance -ConnectionString $MongoUri
          $Database = Get-MongoDBDatabase -DatabaseName $MongoDbName
          $Collection = Get-MongoDBCollection -CollectionName $MongoCollection -MongoDatabase $Database

          #Write-Host "MongoDB connection established and collection retrieved."

          # Loop through each day from StartDate to EndDate and collect metrics
          $CurrentDate = [datetime]::ParseExact($StartDate, "yyyy-MM-dd", $null)
          $EndDate = [datetime]::ParseExact($EndDate, "yyyy-MM-dd", $null)

          while ($CurrentDate -le $EndDate) {
              $FormattedDate = $CurrentDate.ToString("yyyy-MM-dd")

              # Make the API request to YouTube Analytics API to get metrics for the current date
              $QueryParams = @{
                ids         = "channel==${ChannelId}"
                startDate   = $FormattedDate
                endDate     = $FormattedDate
                metrics     = "views,estimatedMinutesWatched,likes"
              }

              # Ensure proper URL encoding
              $EncodedQueryString = ($QueryParams.GetEnumerator() | ForEach-Object {
                "$([System.Web.HttpUtility]::UrlEncode($_.Key))=$([System.Web.HttpUtility]::UrlEncode($_.Value))"
              }) -join "&"

              # Construct the final API URL
              $ApiRequestUrl = "$($ApiUrl)?$($EncodedQueryString)"

              Write-Host "API Request URL: $ApiRequestUrl"  # Debugging output

              # Make the API request
              $Response = Invoke-RestMethod -Uri $ApiRequestUrl -Method Get -Headers @{
                Authorization = "Bearer $AccessToken"
                Accept = "application/json"
              }

              # Map the columns to the corresponding values in the rows
              $ColumnHeaders = $Response.columnHeaders
              $RowData = @()
              foreach ($Row in $Response.rows) {
                  $MappedRow = @{ }
                  for ($i = 0; $i -lt $Row.Count; $i++) {
                      $MappedRow[$ColumnHeaders[$i].name] = $Row[$i]
                  }
                  $RowData += $MappedRow
              }

              # Format data for MongoDB insertion (without platform field)
              $Data = @{
                  date       = $FormattedDate
                  metrics    = $RowData
              }

              # Insert the data into MongoDB
              $Collection.InsertOne($Data)

              Write-Host "YouTube metrics for $FormattedDate inserted into MongoDB successfully."

              # Move to the next day
              $CurrentDate = $CurrentDate.AddDays(1)
          }

      - name: Output result
        run: |
          echo "YouTube metrics backfilled from 2025-01-01 to $(Get-Date -Format 'yyyy-MM-dd')"
