name: Announce Minecraft Stream on Bluesky

on:
  schedule:
    - cron: "0 13 * * 1-5"  # 7:00 AM CST, Mon-Fri (1 hour before Minecraft stream)
  workflow_dispatch:

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Post to Bluesky
        uses: mod-posh/Post2BlueSky@v0.0.2.10
        with:
          message: "Starting the day with some Minecraft adventures! 🛠️ Join me at 8:00 AM CST: `[twitch.tv/sysop71](https://twitch.tv/sysop71)` #Minecraft #MinecraftHardcore #MinecraftSurvival #MinecraftChallenge #GamingCommunity #LetsPlayMinecraft #GamingClips #MinecraftAdventure #GamerLife #StreamHighlights"
          verbose: "verbose"
          bluesky_api_key: ${{ secrets.bluesky_api_key }}
          bluesky_identifier: ${{ secrets.bluesky_identifier }}
