name: Announce Hardcore Stream

on:
  schedule:
    - cron: "30 12 * * 1,3,5"  # 7:30 AM CST on Mon/Wed/Fri
  workflow_dispatch:

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Post to Bluesky
        uses: mod-posh/Post2BlueSky@v0.0.3.0
        with:
          Message: "Hardcore Minecraft starts at 8:00 AM CST! Join in for tense survival and coffee: [twitch.tv/sysop71](https://twitch.tv/sysop71) #MinecraftHardcore #HardcoreSurvival #StreamingNow #LetsPlayMinecraft"
          verbose: "verbose"
          bluesky_api_key: ${{ secrets.bluesky_api_key }}
          bluesky_identifier: ${{ secrets.bluesky_identifier }}

      - name: Post to Discord
        uses: mod-posh/Post2Discord@v0.0.3.2
        with:
          message: "Hardcore Minecraft begins at 8:00 AM CST. Join the stream now: [twitch.tv/sysop71](https://twitch.tv/sysop71)"
          discordWebhook: ${{ secrets.SYSOP71_DISCORD_WEBHOOK }}
