name: Announce Overwatch Stream

on:
  schedule:
    - cron: "0 3 * * 2-4"  # 9:00 PM CST, Tue-Thu (1 hour before Overwatch stream)
  workflow_dispatch:

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true
  
jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Post to Bluesky
        uses: mod-posh/Post2BlueSky@v0.0.3.0
        with:
          message: "Late-night Overwatch grind starts at 10:00 PM CST! Join the fun: [twitch.tv/sysop71](https://twitch.tv/sysop71) #Overwatch2 #OverwatchGameplay #OverwatchFunny #OverwatchPlays #OverwatchCommunity #OverwatchMoments #FPSGaming #GamingClips #GamerLife #StreamHighlights"
          verbose: "verbose"
          bluesky_api_key: ${{ secrets.bluesky_api_key }}
          bluesky_identifier: ${{ secrets.bluesky_identifier }}

      - name: Post to Discord (Sysop71)
        uses: mod-posh/Post2Discord@v0.0.3.2
        with:
          message: "Late-night Overwatch grind starts at 10:00 PM CST! Join the fun: [twitch.tv/sysop71](https://twitch.tv/sysop71)"
          discordWebhook: ${{ secrets.SYSOP71_DISCORD_WEBHOOK }}

      - name: Post to Discord (Games and Stuff)
        uses: mod-posh/Post2Discord@v0.0.3.2
        with:
          message: "Late-night Overwatch grind starts at 10:00 PM CST! Join the fun: [twitch.tv/sysop71](https://twitch.tv/sysop71)"
          discordWebhook: ${{ secrets.GAMESANDSTUFF_DISCORD_WEBHOOK }}
