name: Update Twitch Stream for Minecraft

on:
  schedule:
    - cron: "0 14 * * 1-5"  # Run from 8:00 AM to 9:00 AM CST, Mon-Fri
  workflow_dispatch:  # Manual trigger

jobs:
  update-minecraft:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Refresh OAuth token using refresh token
        shell: pwsh
        run: |
          # Twitch API credentials from repo secrets
          $ClientId = "${{ secrets.CLIENTID }}"
          $ClientSecret = "${{ secrets.CLIENTSECRET }}"
          $RefreshToken = "${{ secrets.REFRESHTOKEN }}"  # GitHub Secret for refresh token

          # Get a new OAuth token using the refresh token
          $TokenResponse = Invoke-RestMethod -Uri "https://id.twitch.tv/oauth2/token" -Method Post -Body @{
              client_id = $ClientId
              client_secret = $ClientSecret
              grant_type = "refresh_token"
              refresh_token = $RefreshToken
          }
          $AccessToken = $TokenResponse.access_token

          # Get game ID for Minecraft
          $GameName = "Minecraft"
          $GameResponse = Invoke-RestMethod -Uri "https://api.twitch.tv/helix/games?name=$GameName" -Headers @{
              "Client-ID" = $ClientId
              "Authorization" = "Bearer $AccessToken"
          }
          $GameId = $GameResponse.data[0].id

          # Update stream info
          $StreamTitle = "Starting the day with some Minecraft adventures!"
          $Tags = @("Minecraft", "MinecraftHardcore", "MinecraftSurvival", "MinecraftChallenge", "GamingCommunity", "LetsPlayMinecraft", "GamingClips", "MinecraftAdventure", "GamerLife", "StreamHighlights")

          $UpdateBody = @{
              title = $StreamTitle
              game_id = $GameId
              broadcaster_id = "${{ vars.BROADCASTERID }}"
              tags = $Tags
          } | ConvertTo-Json -Depth 10

          # Update stream info
          Invoke-RestMethod -Uri "https://api.twitch.tv/helix/channels" -Method Patch -Headers @{
              "Client-ID" = $ClientId
              "Authorization" = "Bearer $AccessToken"
              "Content-Type" = "application/json"
          } -Body $UpdateBody

          Write-Host "Minecraft stream information updated successfully!"
