name: Update Refresh Token Secret

on:
  workflow_dispatch:  # Manually triggered from the UI

jobs:
  update-refresh-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run custom action to update the refresh token secret
        uses: ./.github/actions/update-refresh-token
        with:
          github_token: ${{ secrets.GH_PAT }}
          new_refresh_token: ${{ secrets.NEW_REFRESH_TOKEN }}
