name: Renew Twitch Refresh Token

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  workflow_dispatch:  # Manually triggered from the UI

jobs:
  renew-token:
    runs-on: windows-latest # Use Windows for PowerShell compatibility

    steps:
      # Step 1: Authenticate with Azure
      - name: Authenticate to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 2: Retrieve Existing Token from Azure Key Vault
      - name: Retrieve Existing Token from Azure Key Vault
        id: get-token
        shell: pwsh
        run: |
          $KeyVaultName = "${{ secrets.AZURE_KEYVAULT_NAME }}"
          $SecretName = "Twitch-RefreshToken"
          $RefreshToken = az keyvault secret show --vault-name $KeyVaultName --name $SecretName --query value -o tsv
          if (-not $RefreshToken) {
              Write-Error "Failed to retrieve the refresh token from Azure Key Vault."
              exit 1
          }
          Write-Host "Refresh token retrieved successfully."
          Write-Output "refresh_token=$RefreshToken" | Out-File -FilePath $env:GITHUB_ENV -Append

      # Step 3: Renew the Refresh Token
      - name: Renew the Refresh Token
        id: renew-token
        shell: pwsh
        run: |
          $ClientId = "${{ secrets.CLIENTID }}"
          $ClientSecret = "${{ secrets.CLIENTSECRET }}"
          $RefreshToken = "${{ env.refresh_token }}"

          # Call Twitch API to renew the token
          try {
              $TokenResponse = Invoke-RestMethod -Uri "https://id.twitch.tv/oauth2/token" -Method Post -Body @{
                  client_id     = $ClientId
                  client_secret = $ClientSecret
                  grant_type    = "refresh_token"
                  refresh_token = $RefreshToken
              }
              $NewAccessToken = $TokenResponse.access_token
              $NewRefreshToken = $TokenResponse.refresh_token

              if (-not $NewAccessToken -or -not $NewRefreshToken) {
                  throw "Failed to retrieve new tokens from Twitch."
              }

              Write-Host "New refresh token retrieved successfully."
              Write-Output "new_refresh_token=$NewRefreshToken" | Out-File -FilePath $env:GITHUB_ENV -Append
          } catch {
              Write-Error "An error occurred while renewing the token: $_"
              exit 1
          }

      # Step 4: Update the Token in Azure Key Vault
      - name: Update Token in Azure Key Vault
        shell: pwsh
        run: |
          $KeyVaultName = "${{ secrets.AZURE_KEYVAULT_NAME }}"
          $SecretName = "Twitch-RefreshToken"
          $NewRefreshToken = "${{ env.new_refresh_token }}"

          az keyvault secret set --vault-name $KeyVaultName --name $SecretName --value $NewRefreshToken
          Write-Host "Refresh token successfully updated in Azure Key Vault."
